# Generated by Django 4.2.27 on 2026-03-03 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='insight',
            name='unique_insight_per_user_per_day',
        ),
        migrations.AddField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('SYSTEM', 'System Generated'), ('CHAT', 'Chat Generated')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='insight',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insight',
            name='text',
            field=models.TextField(),
        ),
    ]
