# Generated by Django 4.2.27 on 2026-03-03 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0002_remove_insight_unique_insight_per_user_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_alerts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('health_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('CHAT', 'Chat Generated')], default='CHAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', 'date'], name='insights_in_user_id_5cb7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['created_at'], name='insights_in_created_c34a89_idx'),
        ),
        migrations.AddField(
            model_name='monthlyinsightsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyinsightsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='monthlyinsightsnapshot',
            index=models.Index(fields=['user', 'year', 'month'], name='insights_mo_user_id_60efe1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyinsightsnapshot',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='dailyinsightsnapshot',
            index=models.Index(fields=['user', 'date'], name='insights_da_user_id_a8d6c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyinsightsnapshot',
            unique_together={('user', 'date')},
        ),
    ]
