# Generated by Django 4.2.27 on 2026-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_note_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.CharField(default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=10),
        ),
    ]
