# Generated by Django 4.2.27 on 2026-03-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_recurringtransaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], max_length=10),
        ),
    ]
